### ISSUE TITLE
1.5 Compatibility

### ISSUE THREAD

**Issue by fredngo** [Falconne/ImprovedWorkbenches#108]
Hate to be the one to do it but someone has to I guess...

1.5 came out today so here's the placeholder for the 1.5 upgrade!

**Comment by DavidEnauraBurns** [comment]
Yeah, i'd like to know as well if we will get a 1.5 version? Unsure if Falconne or OwlChemist are gonna be back to update this, hoping they can or if not someone else can fork and update cause count additional items, copy and pasting an entire bench and linking are massive QoL features this mod provides.

**Comment by Falconne** [comment]
Should be updated now
