### ISSUE TITLE
Ability to save bills between games

### ISSUE THREAD

**Issue by boundir** [Falconne/ImprovedWorkbenches#11]
Like the blueprint mod from Fluffy it would be great to be able to save our bills in files which could be used in different playthrough/maps.
When you move from place, or when you start a new game, your bills will almost be the same. For cooking you'll work on Simple Meal, Kibble. Build bows and tribalwear, craft smokes etc...

**Comment by Falconne** [comment]
Support has been added for RimWorld Export Agency to read this mod's data.
