### ISSUE TITLE
Migrate from Enhanced Crafting

### ISSUE THREAD

**Issue by perkinslr** [Falconne/ImprovedWorkbenches#12]
So, the author of Enhanced Crafting recommends switching to this, and I can see why.  Nice job!  The problem is in switching an existing colony over; it's fairly easy to do, but the intro post and github readme don't have instructions for it.  

Step 1:  Make sure nobody is using any of the work benches, firepits, or anything else that has recipes.  Removing the orders from all workbenches might remove the need for step 3, but I've only tried it with a new workbench (never had a bill added to it).
Step 2:  Switch which mod is active in the mod list.  I recommend putting BWM in the same spot you pull EC out of, but it generally won't matter.
Step 3:  Rebuild all work benches, stoves, et cetera.  This can be done easily by going into dev mode->God Mode, insta-building copies of all your production stuff, then using the destroy tool to remove the originals.  If you don't have the minimize-anything mod, you then need to do it again if you want everything in its original position.
Step 4:  Re-add your bills.

**Comment by Falconne** [comment]
Good point, I have now added migration instructions to both the Steam page and the Ludeon thread.

You don't need to deconstruct the workbenches, just removing all the bills will do. Also it shouldn't really matter where this mod is added in the list as long as it's after HugsLib.
