### ISSUE TITLE
Allow setting Drop on Floor as default

### ISSUE THREAD

**Issue by Falconne** [Falconne/ImprovedWorkbenches#23]

**Comment by quicksketch** [comment]
I was searching the workshop specifically for this one feature. I have all my work benches drop on the floor to speed up production time, while my army of huskies puts things in correct piles for my colonists.

**Comment by Falconne** [comment]
I'll do this in the next update

**Comment by quicksketch** [comment]
Hi there @Falconne! Just dropping by to say **thank you**! This is a great new feature and I've enabled it with much success. Works perfectly. Thanks!!

**Comment by Falconne** [comment]
No worries :)
