### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by CellularSuicide** [Falconne/ImprovedWorkbenches#6]
This has suddenly stopped working for me today. I turned off all the mods that had been updated that could have possibly caused this issue, and I still don't get the filters anymore.

**Comment by Falconne** [comment]
So you have HugsLib enabled and this mod after that and then even if you create a new bill after that the filters don't appear?

Can you turn on dev mode and see if anything appears in the output log when you've added a new bill and set it to "Do until X".

**Comment by CellularSuicide** [comment]
So when I turn on Dev mode, it works, but when I turn dev mode off, it doesn't work.

**Comment by CellularSuicide** [comment]
Nevermind. Found the issue, nothing to do with your mod. Thanks for taking the time! Keep doing what you do. I basically need your mod to play the game. Lol

**Comment by Falconne** [comment]
Sweet. What was it? Is it a situation others might run into and get the same problem?

**Comment by CellularSuicide** [comment]
It was an issue with a mod for copying work bills, the filters didn't go along with them.
