### ISSUE TITLE
"Do until X ingredients left"

### ISSUE THREAD

**Issue by Nutzer17** [Falconne/ImprovedWorkbenches#65]
Is it possible to add this mode ? 

Usecase:

- want to leave some spare ingredients for emergency apparel/constructions
- want to spare some herbal meds when making medicine, to not spend neutro on injured prisoners/pets

**Comment by Falconne** [comment]
Yes I had wanted to do this too a while ago, thanks for logging it.

**Comment by alextd** [comment]
Hey! I made this, along with "Do Until X Per colonist" in "Everybody Gets One" : https://steamcommunity.com/sharedfiles/filedetails/?id=1687566130

**Comment by Falconne** [comment]
@alextd  Sweet! I have added a link to your mod from the description for my mod on Steam. Based on your code it looks like the two mods should be compatible. I assume you've tried them both together?

**Comment by alextd** [comment]
Yup - it mostly just re-uses the target count code.

For compatibility, It does apply a patch to Better Workbenches to check for the new repeatmodes
