### ISSUE TITLE
"Count resources outside stockpiles" implemented in 1.1

### ISSUE THREAD

**Issue by CodeOptimist** [Falconne/ImprovedWorkbenches#84]
(First of all, your mod is amazing. One of my essential!)

Counting resources outside stockpiles is now the default behavior in v1.1, so turning "off" this setting in your mod no longer turns it off. I suggest just removing the feature?
Love it! Thanks.

**Comment by Falconne** [comment]
Thanks for letting me know, I'll update that (I haven't actually played since 0.17 so don't always realise these changes)

**Comment by CodeOptimist** [comment]
Oh sorry @Falconne, I double checked and I'm a little mistaken. This feature in your mod **is** still useful.

It looks like 1.1 only added counting outside stockpiles _when a filter (like hit points)_ is set. 1.0 definitely didn't do this, I'm comparing them now. (Hilariously it still has the bug which ignores stack count when a filter is set which both AlexTD and I each fixed in our mods. 😂)

So it's only that _some_ of this feature's code _may_ be redundant in 1.1. (I am actually about to check your code to see if this is even true and if not I was going to delete this Issue but you replied so fast. 😆)

**Comment by CodeOptimist** [comment]
Just tested your mod back on 1.0, and see it didn't patch that bit anyway.
So you can close this, nothing needs changing. Sorry for wasting your time friend!

**Comment by Falconne** [comment]
No worries, thanks for following up
