### ISSUE TITLE
Electric stove refuses to make "Do Until X" fine meals

### ISSUE THREAD

**Issue by Fuitad** [Falconne/ImprovedWorkbenches#9]
Hey there! Loved your mod. It's a real improvement and something I couldn't live without anymore.

I'm having a weird bug in the game I'm in. For some reason, my electric stove refuses to make Fine Meals if I'm using the "Do Until X" mode. No matter what, it stays grayed out and in pause, even if I have all the mats necessary. Worst thing is, if I switch to "Do X times", it'll work just fine.

I uploaded some screenshots for you to see:

- Bills: http://i.imgur.com/fsXyt3s.png
- Bill details: http://i.imgur.com/biDxD4H.png

Do you know what could be the cause? Thanks!

**Comment by Falconne** [comment]
Could you upload your save somewhere along with your mod list? Which mod is adding the unpause button and green numbers to bills list?

**Comment by Fuitad** [comment]
Here's my save file: https://www.dropbox.com/s/9fnu9oanre8zcrc/Sun%20Village.rws?dl=0

I'll have my mod list shortly. As for the green numbers and pause button, I'm not 100% sure. I'll get back to you about that when I post my mod list.

**Comment by Fuitad** [comment]
Here are my list of mods:

- AccuraSight-master
- AllowDeadMansApparel
- AllowTool
- Blueprints
- DefensivePositions
- HeatMap
- HugsLib
- ImprovedWorkbenches
- MedicalTab
- Moody
- MorePlanning
- OmniLocator
- Preset-Filtered-Zones-17.02
- Psychology
- QOLTweaksPack-1.0.2
- RimFridge
- StackMerger
- SupportBeams
- [A17] Quality Cooldown

I'm still trying to find out why mod adds the green numbers and the unpause button... My guess would have been your mod so if it's not that, I'm really not sure...

**Comment by Fuitad** [comment]
Ok I found the mod that adds the green numbers. It's QOLTweaksPack-1.0.2.

https://ludeon.com/forums/index.php?topic=32807.0

The feature is called Meal equivalency

> I like keeping a steady supply of meals. I also like not making simple meals when I could be making fine meals. This tweak makes both of these goals possible to accomplish without micromanaging, as cooks will now consider both simple meals and fine meals when counting meals in storage.

I guess that's what created the conflict. Disabling that mod solved the problem. Sorry for the trouble -_-.

**Comment by Fuitad** [comment]
Confirmed that disabling the Meal equivalency feature in the mod, while keeping it active got rid of the problem. Again, so sorry for the bother.

**Comment by Falconne** [comment]
No worries. It's good to have this logged as others will have the same question in the future. Thanks.
